apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-generator
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: media-generator
  template:
    metadata:
      labels:
        app: media-generator
    spec:
      containers:
      - name: media-generator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: PORT
          value: {{ .Values.env.PORT | quote }}
        - name: ENVIRONMENT
          value: {{ .Values.env.ENVIRONMENT | quote }}
